#!/bin/bash

# set file

file=$1

if [[ $file == "" ]];
then
    echo "No file given"
    exit 1
fi


# Make pdf
pdflatex $file 2&> /dev/null


# Get file name
IFS='.' read -ra f_split <<< "$file"


# Remove .log and .aux
rm "${f_split[0]}.aux"
rm "${f_split[0]}.log"
